Repository AY2526S1-CS2103T-F15a-2/tp, pull requests merged in 2025-10, with the labels that each got.

#14 Add Cyril's photo
  docs/images/cyfake.png
Labels: type.Task, priority.High

#13 Add Zamien's photo
  docs/images/zpnoob.png
Labels: type.Task, priority.High

#24 Update Zamien's About Us Page
  docs/AboutUs.md
  docs/team/zpnoob.md
Labels: priority.High

#23 Create Nicholas' AboutUs Page
  docs/AboutUs.md
  docs/team/lanjia0.md
Labels: type.Task, priority.High, severity.Low

#42 added user profile and value proposition
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#40 Add UI mockup of intended final product
  docs/images/Ui.png
Labels: type.Task, priority.High

#47 Update README.md to acknowledge code source
  README.md
Labels: priority.High
